final Map gamesByCategory = {
  'opening': [
    'Playground Insults',
    'Video Dating Service',
    'Home Shopping',
    'Categories',
    'Try That on for Size',
    'What Are You Doing?',
    'What You Got?',
  ],
  'closing': [
    '5 Things (or 6 Things)',
    'I Can Do Better',
    'Freeze Tag',
    'Day In A Life',
    'Blitzkrieg (or Guess That Thing)',
  ],
  'scene': [
    'Sit, Stand, kneel, Lie',
    'Pavlovian Response',
    'Say Stuff Do Things',
    'Revolving Door',
    'Shakespeare Switch',
    'Blind Line',
    'Countdown',
    'Naive Replay (Mega)',
    'Replay (Emotions, Genres, Mix)',
    'New Choice',
    'New Rhyme',
    'Say That Differently',
  ],
  'afterIntermission': ['Game-O-Matic',],
  'guessing': [
    'Animatronic Jamboree',
    'Chain Murder',
    'Crime Story',
    'Crystal Ball',
    'Dating Game',
    'Hostage Negotiator',
    'Kwazy Quest',
    'Lie Detector',
    'Party Quirks',
    'Sideline Debate',
  ],
  'misc': [
    '1-3-5 (or any numbers)',
    '3/4 Dubbing',
    'Alphabet Genre',
    'Dime-Store Novel',
    'Dr. Know It All Share a Tongue',
    'First Line / Last Line',
    'Foreign Movie',
    'Movie Expert',
    'Oracle',
    'Slow Mo',
    'Replay at Bernie\'s',
    'Teleprompter',
    '4 Rooms',
    'Scene on Book',
    'Scene in Reverse',
    'Skewed',
    '4 Rooms',
    'Questions and Sentences',
    'Wikipedia',
    'Continuation',
    'Pop Up Scene',
    'Dance Party',
    'Mega Replay (Super, Ultra)',
    'Questions',
    'Tag Team Psychotherapist',
    'Tag Team Tale',
    'Town Hall Meeting',
    'Two Minute Expert',
    'Word-At-A-Time Express',
    'World without a Letter',
    'ABC Scene',
    'Telephone',
    'Google Translate',
    'Audience and Hamerstein',
    'Insults Debate, or Dating Service',
    'Family Feud',
    'Subtext',
    'Pick-a-play',
    'Soap Opera',
    'Dawson\'s Creek',
    'Understudy',
    'Radio',
    'Parallel Universe',
    'Hesitation',
    'What a Twist',
    'Last Call',
    'Acromania',
    'Interpreter',
    'Slide Show',
    'Stage Directions',
    'Audition (Screen Test)',
    'Newscaster',
    'Shakespeare',
    'Super Hero',
    'Switch Interview',
    'Talk Radio',
  ],
  'hostInterrupt': [
    'Awkward Moment',
    'Accent Roller Coaster',
    'Big Little',
    'Changing Emotions N\' Stuff',
    'Cut N\' Paste',
    'Deeper',
    'DVD',
    'Forward Reverse',
    'Growing Shrinking Machine',
    'Identity Crisis (Body Snatchers)',
    'Inner Monologue',
    'Oscar Winning Moment',
    'Scantron',
  ],
  'audience': [
    'Text Message',
    'Arms Expert',
    'Audience SFX',
    'Bedtime Story',
    'Campfire Tale',
    'Columns',
    'Timeline',
    'Dinner at Joe\'s',
    'Dubbing',
    'Moving Bodies',
    'Four Square',
    'Siamese Scene',
    'Slide Show',
  ],
  'musical': [
    'Beastie Rap',
    'Broadway Musical',
    'Da-Doo-Ron-Ron/Rap-Rap',
    'Gibberish Opera',
    'Idol American',
    'Inner Song-A-Logue',
    'Irish Drinking Song',
    'Lounge Lizard',
    'Love Song',
    'Madrigal',
    'Musical Chairs',
    'Rap Jam',
    'Rock Opera',
    'Sir Mix-A-Lot (Rap Madrigal)',
    'Sing It',
    'Sing For Your Supper',
    'Songs from a Hat',
    'Word Up From Our Sponsors',
    'Hoedown',
    'Dueling Soundtracks',
    '3/4 Headed Broadway Star',
    'Elimination Rap',
    'Greatest Hits',
  ],
  'standInALine': [
    '185',
    'Back in My Day',
    'Celebrity PUNishment',
    'Hey Waiter',
    'I Kissed A',
    'Last Action Joke',
    'Scenes from a Hat',
    'Sex with Me is Like',
    'What\'d Ya Get?',
    'World\'s Worst',
    'Advice Panel',
    'Good, Bad, & Worst Advice',
    'Instruction Manual',
    'My Movie',
    'Spelling Bee',
    'Story',
    'Boo Yay',
    'Casanova',
    'Limerick',
    'Spelling Bee',
    'Southern Lawyer',
  ],
};