final Map suggestionsByCategory = {
  'locations': [
    "stairwell",
    "bedroom",
    "public bathroom",
    "tropical island",
    "hollywood",
    "Times Square",
    "music festival",
    "concert",
    "eiffel tower",
    "bank",
    "great wall of china",
    "park",
    "theme park",
    "pyramids in egypt",
    "golden gate bridge",
    "stonehenge",
    "grocery store",
    "pharmacy",
    "doctor's office",
    "classroom",
    "library",
    "DMV",
    "police station",
    "firestation",
    "college campus",
    "dorm room",
    "kitchen",
    "family living room",
    "sydney opera house",
    "antarctica",
    "african safari",
    "cave",
    "mount everest",
    "airport",
    "bar",
    "bakery",
    "bookstore",
    "bus station",
    "butcher's shop",
    "cafe",
    "church",
    "courtroom",
    "department store",
    "movie theatre",
    "gym",
    "hair salon",
    "hospital",
    "hotel",
    "museum",
    "laundromat",
    "prison",
    "library",
    "mall",
    "motel",
    "parking lot",
    "post office",
    "school",
    "train station",
    "zoo",
    "the moon",
    "space station",
    "mars",
    "garden",
    "taj mahal",
    "mount rushmore",
    "easter island",
    "leaning tower of pisa",
    "castle",
    "the white house",
    "colosseum",
    "statue of liberty",
    "5 star restaurant",
    "pizza parlor",
    "ice cream shop",
    "bail bonds office",
    "rooftop",
    "fast food restaurant",
    "bouncy house",
    "circus",
    "arcade",
    "auto shop",
    "phonebooth",
    "karaoke bar",
    "state fair",
    "basement",
    "hell",
    "heaven",
    "dungeon",
    "waiting room",
    "emergency room",
    "baseball field",
    "olympic stadium",
    "bowling alley",
    "farmer's market",
    "dark alley",
    "street corner",
    "freeway",
    "tattoo shop",
    "broadway",
  ],
  'people': [
    "doctor",
    "teacher",
    "software engineer",
    "student",
    "nerd",
    "jock",
    "gothic",
    "police officer",
    "fire fighter",
    "paramedic",
    "salesman",
    "scam artist",
    "musician",
    "magician",
    "marketing executive",
    "actor",
    "CEO",
    "mom",
    "dad",
    "bully",
    "grandma",
    "grandpa",
    "brother",
    "sister",
    "maid",
    "executive assistant",
    "pool cleaner",
    "gardener",
    "accountant",
    "teacher",
    "witch",
    "leprecon",
    "wizard",
    "tour guide",
    "travel agent",
    "priest",
    "nun",
    "monk",
    "drug dealer",
    "author",
    "editor",
    "astronaut",
    "valedictorian",
    "mathematician",
    "athlete",
    "funeral director",
    "surgeon",
    "construction worker",
    "volunteer",
    "pilot",
    "architect",
    "mechanical engineer",
    "cartographer",
    "chemist",
    "barista",
    "veterinarian",
    "veteran",
    "soldier",
    "navy seal",
    "photographer",
    "wedding planner",
    "chef",
    "tailor",
    "seamstress",
    "film director",
    "news anchor",
    "dancer",
    "graphic designer",
    "poet",
    "radio personality",
    "referee",
    "pest control",
    "tree trimmer",
    "real estate agent",
    "coroner",
    "detective",
    "auditor",
    "probation officer",
    "inmate",
    "insurance agent",
    "tow truck driver",
    "trucker",
    "judge",
    "auctioneer",
    "mind reader",
    "psychologist",
    "marriage counselor",
    "video game designer",
    "youtube celebrity",
    "taste tester",
    "activist",
    "communist",
    "king",
    "queen",
    "court jester",
    "mom",
    "dad",
    "grandma",
    "grandpa",
    "child",
    "teenager",
    "coach",
    "librarian",
    "nurse",
    "social worker",
    "tutor",
    "farmer",
    "fisherman",
    "boat captain",
    "yacht owner",
    "hunter",
    "hippy",
    "bus driver",
    "dishwasher",
    "flight attendant",
    "server",
    "anesthesiologist",
    "dentist",
    "dermatologist",
    "mechanic",
    "toll collector",
    "meter maid",
    "locksmith",
    "train conductor",
    "clockmaker",
    "historian",
    "park ranger",
    "bill collector",
    "hair stylist",
    "nanny",
    "baker",
    "jewelry maker",
    "potter",
    "quilter",
    "security guard",
    "cashier",
    "telemarketer",
    "superhero",
    "supervillain",
    "elf",
    "troll",
    "vampire",
    "zombie",
  ],
  'things': [
    "dog",
    "bear",
    "flamingo",
    "penguin",
    "cat",
    "mouse",
    "rat",
    "lion",
    "tiger",
    "caterpillar",
    "worm",
    "snail",
    "slug",
    "ant",
    "spider",
    "ostrich",
    "elephant",
    "giraffe",
    "beaver",
    "chihuahua",
    "golden retriever",
    "pitbull",
    "parrot",
    "dinosaur",
    "t-rex",
    "unicorn",
    "dragon",
    "board games",
    "playing cards",
    "pool table",
    "diving board",
    "stool",
    "laundry basket",
    "dishwasher",
    "dryer",
    "rug",
    "chair",
    "table",
    "lamp",
    "mask",
    "globe",
    "basket",
    "painting",
    "artwork",
    "statue",
    "bicycle",
    "motorcycle",
    "car",
    "garage",
    "wrench",
    "bed",
    "dresser",
    "closet",
    "shirt",
    "pants",
    "shoes",
    "socks",
    "underwear",
    "hook",
    "power cord",
    "hair dryer",
    "toothbrush",
    "hair brush",
    "shampoo",
    "soap",
    "loofa",
    "sheets",
    "pillow",
    "carpet",
    "walls",
    "ceiling",
    "roof",
    "storage",
    "refrigerator",
    "freezer",
    "slow cooker",
    "baking sheet",
    "basketball",
    "baseball",
    "roller skates",
    "training wheels",
    "pacifier",
    "diapers",
    "hand sanitizer",
    "broom",
    "mop",
    "vacuum",
    "roomba",
    "ship in a bottle",
    "shower",
    "bathtub",
    "sink",
    "counter",
    "air conditioner",
    "space heater",
    "blender",
    "whisk",
    "straw",
    "bag",
    "purse",
    "vase",
    "mountain",
    "waves",
    "sand",
    "tree",
    "bush",
    "flower",
    "rose",
    "rocks",
    "pebbles",
    "alien",
    "petals",
    "leaf",
    "stick",
    "log",
    "stump",
    "waterfall",
    "lake",
    "ocean",
    "stars",
    "planet",
    "concrete",
    "drill",
    "computer",
    "monitor",
    "thermometer",
    "stethoscope",
    "helicopter",
    "airplane",
    "headphones",
    "phone",
    "pot",
    "pan",
    "spatula",
    "soup ladle",
    "ladder",
    "hammer",
    "nails",
    "projector",
    "slide show",
    "whiteboard",
    "books",
    "diary",
    "ship",
    "anchor",
    "elevator",
    "stairs",
    "pizza",
    "spaghetti",
    "dinner rolls",
    "wheat bread",
    "sourdough",
    "meatballs",
    "pad thai",
    "curry",
    "ramen",
    "slurpee",
    "popsicle",
    "skittles",
    "hersheys",
    "cookies",
    "ice cream",
    "sushi",
    "kimchi",
    "enchiladas",
    "tamales",
    "BBQ",
    "steak",
    "carrots",
    "beets",
    "lettuce",
    "salad",
    "mayonnaise",
    "mustard",
    "ketchup",
    "hotdog",
    "hamburger",
    "peanut butter",
    "sandwich",
    "apple",
    "orange",
    "kiwi",
    "watermelon",
    "popcorn",
    "chips",
    "salsa",
    "granola",
    "cereal",
    "crackers",
    "cheese",
    "wine",
    "beer",
    "cocktail",
    "margarita",
    "moscow mule",
    "mango",
    "pineapple",
    "beans",
    "rice",
    "oven",
    "microwave",
    "bagel",
    "donut",
    "fish",
    "dolphin",
    "snake",
    "shark",
    "lizard",
    "frog",
    "turtle",
    "pigeon",
    "dove",
    "peacock",
    "cow",
    "chicken",
    "horse",
    "donkey",
  ],
};